name: Test
on: push
jobs:
    test:
        name: test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            
            - uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                python-version: 3.11

            - run: conda install numpy gdal requests

            - run: conda list 

            - run: python test.py
        
