name: Test
on: push
defaults:
  run:
    shell: bash -l {0}
jobs:
    test:
        name: test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: mamba-org/setup-micromamba@v1
              with:
                environment-file: environment.yml
                environment-name: env
                condarc: |
                      channels:
                        - conda-forge
                init-shell: bash
            - run: micromamba list 
            - run: python -X dev test.py
